### ISSUE TITLE
Increase meta coverage

### ISSUE THREAD

**Issue by slmnio** [slmnio/slmngg-sfc#97]
The metadata system that provides embed information for services like Discord works pretty well (though could maybe do with including more sites/bots)

It's lacking a lot of coverage of the site and it's not much more than flavour text at this point. A good overhaul should:

- [ ] Part 1: Provide metadata to any valid SLMN.GG link
- [ ] Part 2: Provide useful and human-like responses with data.

By human-like, I mean proper sentences with things like "Atomic is a team from BPL Season 3, captained by Xi. The roster is: Xi, CuteWhiteBoi, Rapha, Varity, Khan, Osiren, Interflux and Doc." and so on

**Comment by slmnio** [comment]
- [ ] /
- [ ] /events
- [ ] /event/:id
  - [ ] /event/
  - [ ] /event/rosters
  - [ ] /event/bracket
  - [ ] /event/brackets (redirect to /bracket - is this something meta should handle?)
  - [ ] /event/schedule
  - [ ] /event/matches (redirects to /schedule)
  - [ ] /event/scenarios
  - [ ] /event/draft
  - [ ] /event/staff
  - [ ] /event/about
  - [ ] /event/standings
- [ ] /teams
- [ ] /team/:id
  - [ ] /team/
  - [ ] /team/matches
  - [ ] /team/theme
  - [ ] /team/details
  - [ ] /team/composition
- [ ] /players
- [ ] /player/:id
  - [ ] /player/
  - [ ] /player/casts
  - [ ] /player/news
  - [ ] /player/matches
  - [ ] /player/played-matches
- [ ] /match/:id
  - [ ] /match/
  - [ ] /match/history
- [ ] /detailed/:id
- [ ] /news/:slug
